### ISSUE TITLE
MutateX crashes when two identical chains don't have the same numbering in multimer mode

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/mutatex#142]
MutateX implicitly assumes that the two chains should have the same numbering, but this is checked for or declared anywhere. If the two chains don't have the same numbering, it sets up mutation runs incorrectly, fails, and exits with a crash:

```
WARNING:root:The following mutation runs failed to complete. The corresponding positions in sequence will be skipped.
WARNING:root:   IB185_IC185
Traceback (most recent call last):
  File "/home/projects/dtu_00011/data/mutatex/mutatex-env/bin/mutatex", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'mutatex')
  File "/home/projects/dtu_00011/data/mutatex/mutatex-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/projects/dtu_00011/data/mutatex/mutatex-env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/projects/dtu_00011/data/mutatex/mutatex-env/lib/python3.9/site-packages/MutateX-0.8-py3.9.egg/EGG-INFO/scripts/mutatex", line 384, in <module>
ValueError: list.remove(x): x not in list
```

We should add a check in which we check for this situation and document it. Also, the program shouldn't just crash - we probably need to fix something with error handling when a mutation run fails

**Comment by aspitaleri** [comment]
Hi - got an identical error:
....
INFO:root:command is /group/davila/SOFTW/COMPCHEM/bin/foldx -f runfile.txt
WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run QA4 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:The following mutation runs failed to complete. The corresponding positions in sequence will be skipped.
WARNING:root:	KA1
Traceback (most recent call last):
  File "/group/davila/ENVS/MDpy3.9/bin/mutatex", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'mutatex')
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1479, in run_script
    exec(script_code, namespace, namespace)
  File "/group/davila/ENVS/MDpy3.9/lib/python3.9/site-packages/MutateX-0.8-py3.9.egg/EGG-INFO/scripts/mutatex", line 385, in <module>
ValueError: list.remove(x): x not in list

Command used is:
mutatex all.pdb \
	-p 4 \
	-u \
        -a \
	-q poslist.txt \
	-m mutation_list.txt \
	-x /group/davila/SOFTW/COMPCHEM/bin/foldx \
	-f suite5 \
        -C deep \
	-S \
	-v \
	-L \
	-c \
	-l 

all.pdb contains 4 models (4 different frames from a MD gromacs simulation). 
Everything was running fine for ~ 1h (3 mutations in poslist and mutations_list contains all aa) and then crashed. Foldx finshed fine (from the output files)

**Comment by mtiberti** [comment]
thanks @aspitaleri - I suspect we have two different problems here:
* One is the problem for which the issue was opened (that might or might not affect you depending on your input PDB) 
* one is mishandling of when a FoldX run fails for whatever reason.

In this case we are seeing the second issue, from the log file:

```
 WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run VA6 was terminated after the repair step, since FoldX found unrecognized molecules.
WARNING:root:run QA4 was terminated after the repair step, since FoldX found unrecognized molecules.
```

this means that during the repair step, FoldX finds residues/molecules it doesn't have parameters for and so deletes them from the PDB. MutateX detects this as an anomalous condition and stops. You should check your repair run, see what this molecule is (there should be a `Unrecognized_molecules.txt` files nd it should say in the FoldX log) and (if it makes sense) remove it from the original PDB(s) before rerunning MutateX. Hope it makes sense to you!

**Comment by aspitaleri** [comment]
Hi @mtiberti  thanks. Indeed the problem was the unrecognized molecules (ASN, which is neutral ASP). I converted to ASP (just residue name, keeping the extra HD2). The repair step was enough to repair. Probably you could catch the error from the pdb residue name (this is what I did - residue list compared to the FoldX residue list accepted).
Best

**Comment by mtiberti** [comment]
@aspitaleri great, happy we understood the problem! And thanks for the suggestion. Let us know if the run completes or you had other issues
