### ISSUE TITLE
Error during the "Report Phase" 

### ISSUE THREAD

**Issue by PaulSchrank** [ELELAB/mutatex#145]
Hello,

First of thanks for providing such a nice tool for automatization of in in silico generation and analysis of site saturation mutagenesis libraries. It  will prove very useful for my work!

Sadly it seems I still have trouble to actually run the plugin, as during the report page I get the messages:

**INFO:root:Parsing file Dif_FRAPD_smTG3_model0_checked_Repair.fxout ...
ERROR:root:Couldn't open or parse file Dif_FRAPD_smTG3_model0_checked_Repair.fxout
ERROR:root:No energy values found in energy files!**

... a dozen of times, than the run will exit. From my understading mutatex will try to parse the fxout files produced by FoldX after the mutation runs, exhibiting the Energy_Diff values, is that correct? So it seems that the fxout files are either missing the information or not generated at all? 

Do you have any suggestion what could be the issue and how to resolve it? 

Thanks in advance!
Paul

For completness sake:

I tried to run a self mutation scan on my protein to test if the repaired structure describes the actual energy minima or if there are still unfavorable rotamers. For this I generated the files: 

-   mutate_runfile_template:

**command=BuildModel
pdb=$PDBS$
mutant-file=site_saturation.txt
water=-CRYSTAL
numberOfRuns=$NRUNS$
complexWithDNA=true**

- repair_runfile_template:

**command=RepairPDB
pdb=$PDBS$

temperature=298
water=-CRYSTAL
complexWithDNA=true**

- pdb file of my protein

and run the job trough the command:

 **mutatex FRAPD_smTG3.pdb --np 4 --nruns 5 --foldx-version suite5 --foldx-log --self-mutate** 

Repair and Mutate steps seem to run without problem, the issue comes up during the report phase

**Comment by mtiberti** [comment]
Hi,

thanks for your feedback - and yes that seems to be the issue - which is quite unusual.

I see you have changed the argument of the `mutant-file` option in your template. MutateX has been designed to automatically handle FoldX mutation runs by using the individual list mechanism - this is done automatically and you don't need to specify any mutation file or similar in the template file(s). MutateX will create the `individual_list.txt` file automatically for every folder but then won't be able to use it because `mutant-file` specifies another filename. So I would recommend to try performing a new run after restoring the `mutant-file` option as it was in the original template.

If you want to specify only some positions to be mutated you can give a position list to MutateX (see position list option in the manual).

Please let me know if this fixes your issue or need more help

**Comment by mtiberti** [comment]
Great it worked alright :) 

Wish you happy mutating!
